name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend (Render Web Service)
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy do backend no Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true

  deploy-frontend:
    name: Deploy Frontend (Render Static Site)
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy do frontend no Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
